include("RBInfo.jl")
include("Snapshots.jl")
include("RBSpace.jl")
include("RBVariable.jl")
include("MDEIMOffline.jl")
#include("MDEIMOnline.jl")

include("PostProcess.jl")

include("ReducedBases.jl")
include("RBOfflineStructure.jl")
include("RBParamOnlineStructure.jl")
include("Coefficient.jl")
include("RBOnlineStructure.jl")
include("RBSystem.jl")
